[project]
name = "odoo-addons-oca-timesheet"
version = "17.0.20240302.0"
dependencies = [
    "odoo-addon-hr_timesheet_task_required>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
